version: '3.8'

services:
  backend:
    build: ./backend
    container_name: zf_halo_backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env # Toma las variables de entorno de tu .env (como DATABASE_URL)
    restart: always

  frontend:
    build: ./frontend
    container_name: zf_halo_frontend
    ports:
      - "5173:80" # Mapea el puerto 80 del Nginx al 5173 de tu máquina
    depends_on:
      - backend
    restart: always